### PR TITLE
add contributing

### PR DESCRIPTION
**Pull request by nphaterp**

### CODE REVIEW

**Review by cmmclaug — CHANGES_REQUESTED** [review]
One thing I would add to this is a section on the process for creating PRs and how we're branching etc. Here's a random example (not using our methodology), but it has a section listing the steps before creating a PR: https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by nphaterp** [comment]
> One thing I would add to this is a section on the process for creating PRs and how we're branching etc. Here's a random example (not using our methodology), but it has a section listing the steps before creating a PR: https://gist.github.com/PurpleBooth/b24679402957c63ec426

heard!

**Review by danielon-5 — APPROVED** [review]

**Comment by nphaterp** [comment]
I added a list of steps based on the link you sent. Honestly, I don't really understand what step 1 is talking about but I still kept it in. What do you guys think.

**Review by CraigEnsemble — APPROVED** [review]
Looks good!

**Review by cmmclaug — APPROVED** [review]
Looks good!

**Pull request merged**
